version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"

  service1:
    build:
      context: ./backend/service1
    container_name: service1
    ports:
      - "8081:8080"

  service2:
    build:
      context: ./backend/service2
    container_name: service2
    ports:
      - "8082:8080"

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - service1
      - service2

